### PR TITLE
Fix mvno_match_data for Telenor DK

### PR DESCRIPTION
**Pull request by mft-dev**

### CODE REVIEW

**Comment by L00N** [comment]
Hey, Michael!

I have a pull just below this one that I think will work better. Could you take a look?

**Comment by mft-dev** [comment]
Hey

I think you're right, there is no reason to have dual carriers with identical information. Why delete the mvno_match_data though? I've tested it and it works for Telenor at least.

**Comment by L00N** [comment]
Can you test if it works without? On bibob it only works without, and they use telenor APN'S now.

```
    Sent by Outlook for Android
```

On Mon, Apr 27, 2015 at 8:34 AM -0700, "Michael" notifications@github.com wrote:
Hey

I think you're right, there is no reason to have dual carriers with identical information. Why delete the mvno_match_data though? I've tested it and it works for Telenor at least.

---

**Comment by mft-dev** [comment]
I'll do some more testing. Preliminary results seem to back you up, though I'm currently unable to get any MMS through. Data works fine with or without mvno

**Comment by L00N** [comment]
Good effort, Sir. Could you perhaps hit me up in a Facebook message? We could do the rest in Danish. I'm new enough here to need assistance pushing mine through GERRIT.

```
    Sent by Outlook for Android
```

On Mon, Apr 27, 2015 at 10:01 AM -0700, "Michael" notifications@github.com wrote:
I'll do some more testing. Preliminary results seem to back you up, though I'm currently unable to get any MMS through. Data works fine with or without mvno

---

**Comment by mft-dev** [comment]
Yeah I have zero experience with the Gerrit process either. I expected the github pulls would be taken up by a maintainer naturally, since lots og commits only show github as the source.

Since the original apns-conf.XML change went through obviously untested, I assume the review process is rather lax.

**Comment by mft-dev** [comment]
Mms works with mvno unset too by the way. Im closing this pull. Feel fred to hit med up on facebook.com/mfthygesen

**Comment by L00N** [comment]
I left you a message. It will probably have gone to the "other" folder.

**Pull request closed without merging**
